version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: techtriathlon_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-tttest}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-tttest}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: techtriathlon_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
    env_file:
      - .env

volumes:
  pgdata:
  uploads:
